# Generated by Django 3.0.5 on 2020-05-09 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_game', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_loss', models.IntegerField(default=0)),
                ('chosen_professor_plum', models.IntegerField(default=0)),
                ('chosen_colonel_mustard', models.IntegerField(default=0)),
                ('chosen_mr_green', models.IntegerField(default=0)),
                ('chosen_mrs_white', models.IntegerField(default=0)),
                ('chosen_ms_scarlet', models.IntegerField(default=0)),
                ('chosen_mrs_peacock', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
