# Generated by Django 3.0.5 on 2020-04-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200411_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creategame',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='creategame',
            name='visibility',
        ),
    ]
