# Generated by Django 3.0.5 on 2020-04-12 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200411_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
