# Generated by Django 3.0.5 on 2020-04-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200412_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='private_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
